import type { Item, Basket } from '@/types';

export const quizQuestions = [
  {
    question: 'Sifat-sifat benda padat adalah sebagai berikut, kecuali...',
    optionA: 'Memiliki bentuk dan volume yang tetap',
    optionB: 'Dapat berubah bentuk dengan cara tertentu',
    optionC: 'Partikel penyusunnya bergerak bebas',
    optionD: 'Tidak bisa mengalir',
    correctAnswer: 'C',
  },
  {
    question: 'Benda cair dapat menempati satu ruang, ini adalah sifat benda cair yang menunjukkan...',
    optionA: 'Massa dan berat benda cair',
    optionB: 'Dapat meresap melalui celah-celah kecil',
    optionC: 'Mengisi seluruh ruang yang ditempatinya',
    optionD: 'Permukaan benda cair yang tenang selalu datar',
    correctAnswer: 'B',
  },
  {
    question: 'Benda gas memiliki sifat berikut, kecuali:',
    optionA: 'Dapat mengisi seluruh ruang yang ditempati',
    optionB: 'Partikel penyusunnya teratur dan rapat',
    optionC: 'Menekan ke segala arah',
    optionD: 'Tidak memiliki bentuk atau volume tetap',
    correctAnswer: 'B',
  },
  {
    question: 'Benda cair dapat melarutkan zat tertentu. Contohnya adalah...',
    optionA: 'Air yang melarutkan garam',
    optionB: 'Es yang melarutkan gula',
    optionC: 'Kayu yang melarutkan minyak',
    optionD: 'Batu yang melarutkan air',
    correctAnswer: 'A',
  },
  {
    question: 'Berikut merupakan contoh dari benda padat yaitu...',
    optionA: 'Plastisin dan Sabun cair',
    optionB: 'Pensil dan susu',
    optionC: 'Meja dan madu',
    optionD: 'Buku dan plastisin',
    correctAnswer: 'D',
  },
  {
    question: 'Air yang berubah menjadi es di dalam freezer adalah contoh perubahan wujud...',
    optionA: 'Mencair',
    optionB: 'Menguap',
    optionC: 'Membeku',
    optionD: 'Mengembun',
    correctAnswer: 'C',
  },
  {
    question: 'Proses perubahan wujud benda yang terjadi ketika air mendidih dan berubah menjadi uap adalah...',
    optionA: 'Mengembun',
    optionB: 'Menguap',
    optionC: 'Menyublim',
    optionD: 'Mencair',
    correctAnswer: 'B',
  },
  {
    question: 'Pengharum ruangan yang lama kelamaan akan habis terkena udara, ini adalah contoh perubahan wujud...',
    optionA: 'Mencair',
    optionB: 'Mengembun',
    optionC: 'Menyublim',
    optionD: 'Menguap',
    correctAnswer: 'C',
  },
  {
    question: 'Apa yang terjadi jika gas dimasukkan ke dalam balon dan ditiupkan...',
    optionA: 'Balon akan menyusut',
    optionB: 'Balon akan mengembang ke segala arah',
    optionC: 'Gas tidak bisa masuk ke dalam balon',
    optionD: 'Balon akan tetap kecil dan tidak berubah',
    correctAnswer: 'B',
  },
  {
    question: 'Proses perubahan wujud benda yang menyebabkan pembentukan salju dari uap air di udara adalah contoh dari...',
    optionA: 'Mengembun',
    optionB: 'Menyublim',
    optionC: 'Membeku',
    optionD: 'Mengkristal',
    correctAnswer: 'D',
  },
  {
    question: 'Salah satu contoh perubahan wujud menyublim adalah...',
    optionA: 'Es batu mencair',
    optionB: 'Kapur barus menguap',
    optionC: 'Minyak menguap saat dipanaskan',
    optionD: 'Air berubah menjadi es',
    correctAnswer: 'B',
  },
  {
    question: 'Manakah pernyataan berikut yang benar mengenai benda cair...',
    optionA: 'Benda cair memiliki bentuk dan volume yang tetap',
    optionB: 'Benda cair bisa berubah bentuk sesuai dengan wadahnya',
    optionC: 'Benda cair tidak dapat mengalir',
    optionD: 'Benda cair tidak memiliki massa',
    correctAnswer: 'B',
  },
  {
    question: 'Contoh benda gas dalam kehidupan sehari-hari adalah...',
    optionA: 'Batu bata',
    optionB: 'Es batu',
    optionC: 'Udara',
    optionD: 'Kayu',
    correctAnswer: 'C',
  },
  {
    question: 'Proses perubahan wujud yang terjadi saat air yang ada di dalam gelas mengembun pada bagian luar gelas adalah contoh dari...',
    optionA: 'Menyublim',
    optionB: 'Menguap',
    optionC: 'Mengembun',
    optionD: 'Mencair',
    correctAnswer: 'C',
  },
  {
    question: 'Salah satu contoh benda padat yang bisa diubah bentuknya adalah...',
    optionA: 'Es batu',
    optionB: 'Air',
    optionC: 'Tanah liat',
    optionD: 'Minyak',
    correctAnswer: 'C',
  },
  {
    question: 'Proses perubahan wujud yang terjadi ketika lilin yang dipanaskan akan mencair dan kembali mengeras adalah contoh dari...',
    optionA: 'Mencair dan membeku',
    optionB: 'Menguap dan mengembun',
    optionC: 'Menyublim dan mengembun',
    optionD: 'Mengkristal dan menguap',
    correctAnswer: 'A',
  },
  {
    question: 'Ketika es batu dibiarkan di suhu ruangan, es tersebut akan mencair. Ini adalah contoh perubahan wujud dari...',
    optionA: 'Padat ke gas',
    optionB: 'Gas ke padat',
    optionC: 'Padat ke cair',
    optionD: 'Cair ke gas',
    correctAnswer: 'C',
  },
  {
    question: 'Apa yang terjadi pada air jika dipanaskan terus menerus hingga mendidih...',
    optionA: 'Air akan mengembun',
    optionB: 'Air akan mencair',
    optionC: 'Air akan menguap',
    optionD: 'Air akan membeku',
    correctAnswer: 'C',
  },
  {
    question: 'Manakah dari berikut ini yang merupakan contoh perubahan wujud benda yang terjadi akibat pendinginan...',
    optionA: 'Mencair',
    optionB: 'Mengembun',
    optionC: 'Menguap',
    optionD: 'Menyublim',
    correctAnswer: 'B',
  },
  {
    question: 'Proses perubahan wujud yang menyebabkan air laut berubah menjadi butiran-butiran garam adalah contoh dari...',
    optionA: 'Mengembun',
    optionB: 'Menyublim',
    optionC: 'Mengkristal',
    optionD: 'Mencair',
    correctAnswer: 'C',
  },
];

export const items: Item[] = [
  { id: '1', name: 'Kursi', imageUrl: '/basket/kursi.png', type: 'PADAT' },
  { id: '2', name: 'Air', imageUrl: '/basket/air.png', type: 'CAIR' },
  { id: '3', name: 'Balon', imageUrl: '/basket/balon.png', type: 'GAS' },
  { id: '4', name: 'Buku', imageUrl: '/basket/buku.png', type: 'PADAT' },
  { id: '5', name: 'Susu', imageUrl: '/basket/susu.png', type: 'CAIR' },
  { id: '6', name: 'Asap', imageUrl: '/basket/uap.png', type: 'GAS' },
  { id: '13', name: 'Saus', imageUrl: '/basket/saus.png', type: 'CAIR' },
  { id: '7', name: 'Penggaris', imageUrl: '/basket/penggaris.png', type: 'PADAT' },
  { id: '9', name: 'Uap', imageUrl: '/basket/awan.png', type: 'GAS' },
  { id: '8', name: 'Minyak', imageUrl: '/basket/minyak.png', type: 'CAIR' },
  { id: '22', name: 'Lampu', imageUrl: '/basket/lampu.png', type: 'PADAT' },
  { id: '11', name: 'Udara', imageUrl: '/basket/udara.png', type: 'GAS' },
  { id: '12', name: 'Kecap', imageUrl: '/basket/kecap.png', type: 'CAIR' },
  { id: '21', name: 'Keju', imageUrl: '/basket/keju.png', type: 'PADAT' },
  { id: '14', name: 'Sabun', imageUrl: '/basket/sabun.png', type: 'CAIR' },
  { id: '19', name: 'Kelereng', imageUrl: '/basket/kelereng.png', type: 'PADAT' },
  { id: '16', name: 'Selai', imageUrl: '/basket/selai.png', type: 'CAIR' },
  { id: '18', name: 'Baju', imageUrl: '/basket/baju.png', type: 'PADAT' },
  { id: '23', name: 'Sabun batang', imageUrl: '/basket/daging.png', type: 'PADAT' },
  { id: '17', name: 'Jus', imageUrl: '/basket/jus.png', type: 'CAIR' },
  { id: '20', name: 'Penghapus', imageUrl: '/basket/penghapus.png', type: 'PADAT' },
  { id: '15', name: 'Oli', imageUrl: '/basket/oli.png', type: 'CAIR' },
  { id: '24', name: 'Figura', imageUrl: '/basket/figura.png', type: 'PADAT' },
];

export const baskets: Basket[] = [
  { id: 'basket-1', type: 'PADAT', label: 'Padat', items: [] },
  { id: 'basket-2', type: 'CAIR', label: 'Cair', items: [] },
  { id: 'basket-3', type: 'GAS', label: 'Gas', items: [] },
];
